export class Icon {
    static options: string[] =
        [
            'fal fa-tag',
            'fal fa-wrench',
            'fal fa-utensils',
            'fal fa-home',
            'fal fa-tv',
            'fal fa-tshirt',
            'fal fa-tools',
            'fal fa-taxi',
            'fal fa-train',
            'fal fa-subway',
            'fal fa-store',
            'fal fa-poop',
            'fal fa-shopping-cart',
            'fal fa-shopping-basket',
            'fal fa-school',
            'fal fa-book-open',
            'fal fa-plane',
            'fal fa-piggy-bank',
            'fal fa-wifi',
            'fal fa-phone',
            'fal fa-money-bill',
            'fal fa-mobile',
            'fal fa-medkit',
            'fal fa-medal',
            'fal fa-heart',
            'fal fa-hamburger',
            'fal fa-gift',
            'fal fa-gas-pump',
            'fal fa-futbol',
            'fal fa-folder',
            'fal fa-file',
            'fal fa-dollar-sign',
            'fal fa-credit-card',
            'fal fa-coffee',
            'fal fa-chart-bar',
            'fal fa-bus',
            'fal fa-bookmark',
            'fal fa-barcode',
            'fal fa-clipboard',
            'fal fa-dumbbell',
            'fal fa-donate',
            'fal fa-wallet'
        ];
}